# -*- coding: utf-8 -*-
"""Predicting_Customer_Outcomes final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l4JeIOQFcj1DxS9h8A0gEEQop_yYIhsZ

# **Import Required Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pandas.plotting import scatter_matrix
import plotly.express as px
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
import xgboost as xgb
from sklearn.metrics import roc_curve, roc_auc_score, confusion_matrix, auc
import warnings
warnings.filterwarnings('ignore')

"""# **Load the Dataset**"""

# Load the dataset into a dataframe
Customer_Outcomes_Dataset = pd.read_csv("dataset.csv", encoding='latin1')

# Display first few rows to understand the data
print(Customer_Outcomes_Dataset.head())

"""# Check for Missing Values"""

# Check for missing values in each column
missing_values = Customer_Outcomes_Dataset.isnull().sum()

# Display missing values per column
print("Missing Values per Column:\n", missing_values)

"""# **Check for Duplicates**"""

# Check for duplicate rows
duplicates = Customer_Outcomes_Dataset.duplicated().sum()

# Display the number of duplicate rows
print("Number of Duplicate Rows:", duplicates)

"""# **Check Data Types (Data Info)**"""

# Check the data types of each column
data_info = Customer_Outcomes_Dataset.info()

# Display the data types of the dataset
print("Dataset Info:\n", data_info)

"""# **Check Shape of the Data**"""

# Check the shape (rows, columns) of the dataset
shape = Customer_Outcomes_Dataset.shape

# Display the shape of the dataset
print("Shape of the Dataset:", shape)

"""# **Descriptive Statistics**"""

# Display descriptive statistics
desc_stats = Customer_Outcomes_Dataset.describe()

# Print the descriptive statistics
print("Descriptive Statistics:\n", desc_stats)

"""# **Plot Histograms for Distribution of Each Column**"""

# Plot histograms for all numeric columns to check the distributions
Customer_Outcomes_Dataset.hist(bins=15, figsize=(15, 10), color='#3498db', edgecolor='black')
plt.suptitle("Distribution of Features")
plt.tight_layout()
plt.show()

"""# **Boxplot for Feature Distributions**"""

# Boxplot to check for outliers in the features
plt.figure(figsize=(20, 10)) # Increased figure size for better label visibility
sns.boxplot(data=Customer_Outcomes_Dataset, palette="hsv")
plt.xticks(rotation=90) # Rotate labels by 90 degrees to prevent overlapping
plt.title('Boxplot of Features (Outlier Detection)') # Added a title for clarity
plt.tight_layout() # Adjust layout to prevent labels from being cut off
plt.show()

"""# **Countplot for Categorical Features (Target Variable)**"""

# Countplot for the target variable
plt.figure(figsize=(8, 6))
sns.countplot(x='Target', data=Customer_Outcomes_Dataset, palette='plasma')
plt.title("Distribution of Target Variable")
plt.show()

"""# **Compute the Correlation Matrix**"""

# Select numeric columns (int64 and float64)
numeric_columns = Customer_Outcomes_Dataset.select_dtypes(include=[np.number])

# Compute the correlation matrix
correlation_matrix = numeric_columns.corr()

# Display the correlation matrix
print("Correlation Matrix:\n", correlation_matrix)

plt.figure(figsize=(12, 8))
sns.heatmap(correlation_matrix, annot=True, fmt='.2f', cmap='Spectral', linewidths=0.5)
plt.title('Correlation Matrix of Numeric Features')
plt.show()

"""# **Convert Categorical Variables**

# **Convert Categorical Variables to Numeric (Target column)**
"""

Customer_Outcomes_Dataset['Target'] = Customer_Outcomes_Dataset['Target'].map({'Graduate': 1, 'Dropout': 0})

"""# **Separate Features (X) and Target Variable (y)**"""

# Drop rows where 'Target' is NaN after conversion
Customer_Outcomes_Dataset.dropna(subset=['Target'], inplace=True)

X = Customer_Outcomes_Dataset.drop(columns=['Target'])  # Features
y = Customer_Outcomes_Dataset['Target']  # Target variable

print(f"Data Types of Each Column:\n{Customer_Outcomes_Dataset.dtypes}\n")

"""# **Split the Data into Training and Testing Sets**"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"Training Set Size: {X_train.shape}")
print(f"Testing Set Size: {X_test.shape}")

"""# **Feature Scaling (Standardization)`**"""

scaler = StandardScaler()

# Fit the scaler on the training set and transform both training and testing sets
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""# **XGBoost Model**"""

# Initialize XGBoost model
xgb_model = xgb.XGBClassifier(random_state=42)

# Train the XGBoost model
xgb_model.fit(X_train_scaled, y_train)

# Make predictions
y_pred_xgb = xgb_model.predict(X_test_scaled)

# Calculate performance metrics
accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
precision_xgb = precision_score(y_test, y_pred_xgb)
recall_xgb = recall_score(y_test, y_pred_xgb)
f1_xgb = f1_score(y_test, y_pred_xgb)
conf_matrix_xgb = confusion_matrix(y_test, y_pred_xgb)
class_report_xgb = classification_report(y_test, y_pred_xgb)

# Print evaluation results
print("XGBoost Model Performance:")
print(f"Accuracy: {accuracy_xgb}")
print(f"Precision: {precision_xgb}")
print(f"Recall: {recall_xgb}")
print(f"F1 Score: {f1_xgb}")
print(f"Confusion Matrix:\n{conf_matrix_xgb}")
print(f"Classification Report:\n{class_report_xgb}")

"""# **AdaBoost Model**"""

# Initialize AdaBoost model
ada_model = AdaBoostClassifier(random_state=42)

# Train the AdaBoost model
ada_model.fit(X_train_scaled, y_train)

# Make predictions
y_pred_ada = ada_model.predict(X_test_scaled)

# Calculate performance metrics
accuracy_ada = accuracy_score(y_test, y_pred_ada)
precision_ada = precision_score(y_test, y_pred_ada)
recall_ada = recall_score(y_test, y_pred_ada)
f1_ada = f1_score(y_test, y_pred_ada)
conf_matrix_ada = confusion_matrix(y_test, y_pred_ada)
class_report_ada = classification_report(y_test, y_pred_ada)

# Print evaluation results
print("AdaBoost Model Performance:")
print(f"Accuracy: {accuracy_ada}")
print(f"Precision: {precision_ada}")
print(f"Recall: {recall_ada}")
print(f"F1 Score: {f1_ada}")
print(f"Confusion Matrix:\n{conf_matrix_ada}")
print(f"Classification Report:\n{class_report_ada}")

"""# **Logistic Regression Model**"""

# Initialize Logistic Regression model
logreg_model = LogisticRegression(random_state=42)

# Train the Logistic Regression model
logreg_model.fit(X_train_scaled, y_train)

# Make predictions
y_pred_logreg = logreg_model.predict(X_test_scaled)

# Calculate performance metrics
accuracy_logreg = accuracy_score(y_test, y_pred_logreg)
precision_logreg = precision_score(y_test, y_pred_logreg)
recall_logreg = recall_score(y_test, y_pred_logreg)
f1_logreg = f1_score(y_test, y_pred_logreg)
conf_matrix_logreg = confusion_matrix(y_test, y_pred_logreg)
class_report_logreg = classification_report(y_test, y_pred_logreg)

# Print evaluation results
print("Logistic Regression Model Performance:")
print(f"Accuracy: {accuracy_logreg}")
print(f"Precision: {precision_logreg}")
print(f"Recall: {recall_logreg}")
print(f"F1 Score: {f1_logreg}")
print(f"Confusion Matrix:\n{conf_matrix_logreg}")
print(f"Classification Report:\n{class_report_logreg}")

"""# **Decision Tree Model**



"""

# Initialize Decision Tree model
dt_model = DecisionTreeClassifier(random_state=42)

# Train the Decision Tree model
dt_model.fit(X_train_scaled, y_train)

# Make predictions
y_pred_dt = dt_model.predict(X_test_scaled)

# Calculate performance metrics
accuracy_dt = accuracy_score(y_test, y_pred_dt)
precision_dt = precision_score(y_test, y_pred_dt)
recall_dt = recall_score(y_test, y_pred_dt)
f1_dt = f1_score(y_test, y_pred_dt)
conf_matrix_dt = confusion_matrix(y_test, y_pred_dt)
class_report_dt = classification_report(y_test, y_pred_dt)

# Print evaluation results
print("Decision Tree Model Performance:")
print(f"Accuracy: {accuracy_dt}")
print(f"Precision: {precision_dt}")
print(f"Recall: {recall_dt}")
print(f"F1 Score: {f1_dt}")
print(f"Confusion Matrix:\n{conf_matrix_dt}")
print(f"Classification Report:\n{class_report_dt}")

"""# **Model Comparison**"""

# Calculate AUC for each model
y_prob_xgb = xgb_model.predict_proba(X_test_scaled)[:, 1]
auc_xgb = roc_auc_score(y_test, y_prob_xgb)

y_prob_ada = ada_model.predict_proba(X_test_scaled)[:, 1]
auc_ada = roc_auc_score(y_test, y_prob_ada)

y_prob_dt = dt_model.predict_proba(X_test_scaled)[:, 1]
auc_dt = roc_auc_score(y_test, y_prob_dt)

y_prob_logreg = logreg_model.predict_proba(X_test_scaled)[:, 1]
auc_logreg = roc_auc_score(y_test, y_prob_logreg)

# Create a DataFrame to compare models
comparison_df = pd.DataFrame({
    'XGBoost': [accuracy_xgb, precision_xgb, recall_xgb, f1_xgb, auc_xgb],
    'AdaBoost': [accuracy_ada, precision_ada, recall_ada, f1_ada, auc_ada],
    'Decision Tree': [accuracy_dt, precision_dt, recall_dt, f1_dt, auc_dt],
    'Logistic Regression': [accuracy_logreg, precision_logreg, recall_logreg, f1_logreg, auc_logreg]
}, index=['Accuracy', 'Precision', 'Recall', 'F1 Score', 'AUC'])

# Transpose for easier plotting
comparison_df = comparison_df.T

metrics_to_plot = ['Accuracy', 'Precision', 'Recall', 'F1 Score']
palettes = ['viridis', 'plasma', 'cividis', 'magma'] # Different palettes for each plot

# Set the style for the plot
sns.set(style="whitegrid")

# Plot for each metric
for i, metric in enumerate(metrics_to_plot):
    plt.figure(figsize=(10, 6))
    ax = sns.barplot(x=comparison_df.index, y=comparison_df[metric], palette=palettes[i % len(palettes)])
    plt.title(f'Model Comparison - {metric}', fontsize=16)
    plt.xlabel('Models', fontsize=12)
    plt.ylabel(f'{metric} Score', fontsize=12)
    plt.ylim(0, 1) # Set y-axis limit for scores
    plt.xticks(rotation=45, ha='right')

    # Add data labels
    for p in ax.patches:
        ax.annotate(format(p.get_height(), '.3f'),
                       (p.get_x() + p.get_width() / 2., p.get_height()),
                       ha = 'center', va = 'center',
                       xytext = (0, 9),
                       textcoords = 'offset points')

    plt.tight_layout()
    plt.show()